### ISSUE TITLE
Help me: SyntaxError: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by alexdo83** [simon-dutka/ai-video-maker#1] opened 2024-03-03 02:06 UTC
Help me: SyntaxError: f-string expression part cannot include a backslash

![Untitled](https://github.com/simon-dutka/ai-video-maker/assets/25850343/6dfc2ca4-9a18-42e0-8ed9-c09fa24da508)

**Comment by simon-dutka** [comment] 2024-03-05 21:49
Hi, try using Python version 3.12

**Comment by Navio1430** [comment] 2024-03-05 21:50
From your screenshot I suppose that you are using Python 10 which may the cause of the error.

Try using newer version of Python.

**Comment by simon-dutka** [comment] 2024-03-15 10:01
Fixed in pull request: "Fix f-string syntax #2"

**Closed** 2024-03-15 10:00 UTC
